/// Flutter icons CoustmIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CoustmIcons
///      fonts:
///       - asset: fonts/CoustmIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CoustmIcons {
  CoustmIcons._();

  static const _kFontFam = 'CoustmIcons';
  static const String? _kFontPkg = null;

  static const IconData github_circled = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube_squared = IconData(0xf166, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
